// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"NRP_WordWrap","status":true,"description":"v1.02 Automatically wraps text by words.","parameters":{"<Scope of Application>":"","AllWindows":"false","Window_Message":"false","Window_Help":"false","Window_ScrollText":"false","AddWindowList":"","<Prohibited Characters>":"","BeginingProhibitedType":"0","BeginingProhibitedCharacters":""}},
{"name":"MoveTitleMenu","status":true,"description":"將標題選單移動到右上角","parameters":{}},
{"name":"ButtonPicture","status":true,"description":"Makes a picture clickable.","parameters":{}},
{"name":"GALV_VisualNovelChoicesMZ","status":false,"description":"(v.1.0) Changes how the \"Choice\" message boxes display to appear more like visual novels.","parameters":{"Command Width":"700","Command Height":"48","Always Middle":"true","Message Gap":"0","Disabled Button":"3"}},
{"name":"GALV_StepEffectsMZ","status":true,"description":"(v.1.1) Spawn events, run common event or other effect when player or event steps on a tile","parameters":{"terrains":"","regions":"","eTerrains":"","eRegions":""}},
{"name":"GeoGebraQuiz","status":true,"description":"GeoGebra 数学测验插件 v1.0","parameters":{}},
{"name":"Complex3Quiz","status":true,"description":"Complex3 连接器 v7.0 —— GameBoy 配色，只冻结玩家移动，放行鼠标","parameters":{}},
{"name":"KJ_Cursor","status":true,"description":"Cursor V1.02 修复冲突","parameters":{"Method":"1","Name":"Cursor","PicSizeX":"32","PicSizeY":"32","Click":"true"}},
{"name":"ASJigsawGame","status":false,"description":"【V1.0.2】拼图小游戏","parameters":{}},
{"name":"JigsawGame","status":false,"description":"【V1.1.0】拼图小游戏 - 支持整图切割与坐标设置","parameters":{}}
];
